UPDATE Defines
SET Value = 0
WHERE Name IN (
	'FRIENDS_CULTURE_BONUS_AMOUNT_ANCIENT',
	'FRIENDS_CULTURE_BONUS_AMOUNT_MEDIEVAL',
	'FRIENDS_CULTURE_BONUS_AMOUNT_INDUSTRIAL',
	'ALLIES_CULTURE_BONUS_AMOUNT_ANCIENT',
	'ALLIES_CULTURE_BONUS_AMOUNT_MEDIEVAL',
	'ALLIES_CULTURE_BONUS_AMOUNT_INDUSTRIAL',
	'FRIENDS_CAPITAL_FOOD_BONUS_AMOUNT_PRE_RENAISSANCE',
	'FRIENDS_CAPITAL_FOOD_BONUS_AMOUNT_POST_RENAISSANCE',
	'FRIENDS_OTHER_CITIES_FOOD_BONUS_AMOUNT_PRE_RENAISSANCE',
	'FRIENDS_OTHER_CITIES_FOOD_BONUS_AMOUNT_POST_RENAISSANCE',
	'ALLIES_CAPITAL_FOOD_BONUS_AMOUNT',
	'ALLIES_OTHER_CITIES_FOOD_BONUS_AMOUNT'
);

UPDATE Defines
SET Value = ROUND(Value * 1.25,0)
WHERE Name IN (
	'WAR_QUEST_COMPLETE_FRIENDSHIP',
	'MINOR_QUEST_FRIENDSHIP_ROUTE',
	'MINOR_QUEST_FRIENDSHIP_KILL_CAMP',
	'MINOR_QUEST_FRIENDSHIP_CONNECT_RESOURCE',
	'MINOR_QUEST_FRIENDSHIP_CONSTRUCT_WONDER',
	'MINOR_QUEST_FRIENDSHIP_GREAT_PERSON',
	'MINOR_QUEST_FRIENDSHIP_FIND_PLAYER',
	'MINOR_QUEST_FRIENDSHIP_FIND_NATURAL_WONDER',
	'MINOR_LIBERATION_FRIENDSHIP'
);

--UPDATE Units
--SET HurryCostModifier = 25
--WHERE CombatClass = 'UNITCOMBAT_DIPLOMACY';